exports.phrases = [
	'wild west',
	'the rolling stones',
	'prison break',
	'addiction',
	'bookworm',
	'death metal',
	'american dream',
	'french toast',
	'fast food',
	'science',
	'curiosity killed a cat',
	'cheatsheet',
	'milky way',
	'solar system',
	'dead end',
	'break a leg',
	'shopping at the mall',
	'going bowling',
	'building a campfire',
	'flying a kite',
	'feeding the ducks',
	'playing chess',
	'making a pizza',
	'playing football',
	'visiting the zoo',
	'flipping pancakes',
	'mowing a lawn',
	'building a sandcastle',
	'delivering mail',
	'landing an airplane',
	'building a campfire',
	'kung-fu panda',
	'jaws',
	'black swan',
	'iron man',
	'the lion king',
	'shrek',
	'titanic',
	'ghostbusters',
	'toy story',
	'the matrix',
	'twilight',
	'home alone',
	'the simpsons'
	'south park',
	'game of thrones',
	'futurama',
	'smurfs',
	'south park',
	'harry potter',
	'the hobbit'
];
