exports.phrases = [
	'wild west',
	'the rolling stones',
	'prison break',
	'addiction',
	'bookworm',
	'death metal',
	'american dream',
	'french toast',
	'fast food',
	'science',
	'curiosity killed a cat',
	'cheatsheet',
	'milky way',
	'solar system',
	'dead end',
	'break a leg',
	'shopping at the mall',
	'going bowling',
	'building a campfire',
	'flying a kite',
	'feeding the ducks',
	'playing chess',
	'making a pizza',
	'playing football',
	'visiting the zoo',
	'flipping pancakes',
	'mowing a lawn',
	'building a sandcastle',
	'delivering mail',
	'landing an airplane',
	'building a campfire',
];
